-- MySQL Script generated by MySQL Workbench
-- Mon Apr  6 22:41:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myreceitas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myreceitas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myreceitas` DEFAULT CHARACTER SET utf8 ;
USE `myreceitas` ;

-- -----------------------------------------------------
-- Table `myreceitas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myreceitas`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `slug` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreceitas`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myreceitas`.`receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(120) NOT NULL,
  `linha_fina` VARCHAR(250) NOT NULL,
  `descricao` TEXT NOT NULL,
  `thumb` VARCHAR(100) NOT NULL,
  `data` DATETIME NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receita_categoria_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_receita_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `myreceitas`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
